- name: Terraform Apply
  run: |
    terraform apply -auto-approve \
      -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
      -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
      -var="region=${REGION}" \
      -var="account_id=${ACCOUNT_ID}" \
      -var="account_name=${ACCOUNT_NAME}" \
      -var="vpc_cidr=${VPC_CIDR}" \
      -var="vpc_required=${VPC_REQ}" \
      -var="environment=${ENV}" \
      -var="request_id=${REQ_ID}"
  working-directory: env
